theme = "sonokai"

[editor]
rulers = [80]
cursorline = true
cursorcolumn = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.indent-guides]
character = "┊"
render = true

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"    # Non Breaking SPace
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.statusline]
left = [ "mode", "spinner", "diagnostics" ]
center = [ "file-name", "separator", "version-control", "separator" ]
right = [ "position", "position-percentage", "total-line-numbers" ]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
g = { a = "code_action" } # Maps `ga` to show possible code actions
0 = "goto_line_start"
"$" = "goto_line_end"
"G" = "goto_last_line"
"D" = "@vgld"
"F" = ":toggle-option auto-format"
"backspace" = "move_char_left"
C-r = ":config-reload"
"H" = ":buffer-previous"
"L" = ":buffer-next"
"ret" = "move_visual_line_down"
C-o = { "c"=":open ~/.config/helix/config.toml", "l"=":open ~/.config/helix/languages.toml" }
z = { g = [":pipe-to vale-add-word", ":lsp-restart"] }

 
# Use system clipboard
p = "paste_clipboard_before"
y = "yank_main_selection_to_clipboard"

[keys.select]
"G" = "goto_last_line"

