theme = "sonokai"

[editor]
rulers = [80]
cursorline = true
cursorcolumn = true
bufferline = "always"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"    # Non Breaking SPace
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.statusline]
left = [ "mode", "spinner", "diagnostics" ]
center = [ "file-name", "separator", "version-control", "separator" ]
right = [ "position", "position-percentage", "total-line-numbers" ]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
0 = "goto_line_start"
"$" = "goto_line_end"
"G" = "goto_last_line"
"D" = "@vgld"
"F" = ":toggle-option auto-format"
"backspace" = "move_char_left"
